

services:
  tamangteppiche-db:
    container_name: tamangteppiche-db
    image: postgres:latest
    environment:
      POSTGRES_USER: tamangteppicheuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tamangteppichedb
    ports:
      - "5434:5432"
    volumes:
      - tamangteppiche-pgdata:/var/lib/postgresql/data

volumes:
  tamangteppiche-pgdata: {}